version: "3.7"
services:
  app:
    build: .
    ports:
      - 8080:8080
    depends_on:
      - mongodb
    command: bash -c "until nc -z mongodb 27017; do echo Waiting for MongoDB; sleep 1; done; java -jar app.jar"
  mongodb:
    image: mongo:4.4.3
    ports:
      - 27017:27017